const ARTISTS = [
  "Al Jaffee",
  "Alex Ross",
  "Ansel Adams",
  "Andy Warhol",
  "Banksy",
  "Claude Monet",
  "Chuck Jones",
  "Drew Struzan",
  "Edvard Munch",
  "Frida Kahlo",
  "Greg Rutkowski",
  "Jack Davis",
  "Jack Kirby",
  "Jan Vermeer",
  "Jim Lee",
  "Leonardo da Vinci",
  "Michelangelo",
  "Pablo Picasso",
  "Rembrandt",
  "Salvador Dali",
  "Sergio Aragones",
  "Vincent van Gogh",
  "Walt Disney",
];

const ART_STYLES = [
  "3d printed",
  "3d render",
  "abstract",
  "anime",
  "art deco",
  "art nouveau",
  "baroque",
  "bauhaus",
  "beaux arts",
  "biedermeier",
  "brutalist architecture",
  "buddhist art",
  "calligraphy",
  "caricature",
  "cartoon",
  "catholic",
  "cel shading",
  "celtic",
  "chinese calligraphy",
  "chinese ink",
  "chinese painting",
  "chinese seal",
  "crochet",
  "cubism",
  "cubist painting",
  "cubist sculpture",
  "cubist",
  "dreamworks",
  "dutch renaissance",
  "early renaissance",
  "expressionism",
  "flat shading",
  "forced perspective",
  "french impressionism",
  "futurism",
  "geometric",
  "gothic",
  "graffiti",
  "graphic design",
  "grisaille",
  "harlem renaissance",
  "hyperrealism",
  "impressionist",
  "metal hurlant",
  "minimalist",
  "modernism",
  "octane render",
  "oil painting",
  "old master",
  "painterly",
  "painting",
  "paper cutout",
  "pastel drawing",
  "pencil drawing",
  "pencil sketch",
  "photorealism",
  "photorealistic",
  "pixar",
  "pointillism",
  "pop art",
  "portrait",
  "portraiture",
  "post-impressionism",
  "poster",
  "postmodernism",
  "pre-raphaelite",
  "psychedelic",
  "realism",
  "realist",
  "renaissance",
  "romanticism",
  "russian constructivism",
  "sculpture",
  "sketch",
  "silhouette",
  "simplistic",
  "still life",
  "stipple",
  "surrealism",
  "surrealist",
  "tachisme",
  "tachist",
  "typography",
  "unreal engine",
  "urban",
  "vaporwave",
  "vector art",
  "victorian era",
  "vintage",
  "watercolor",
  "woodcut",
];

const GALLERIES = ["artstation", "cgsociety"];

const CAMERA_ATTR = [
  "35mm f1.8",
  "analog photo",
  "anamorphic lens",
  "bird's eye view",
  "bokeh",
  "close up",
  "colorful",
  "dof",
  "distant view",
  "dof",
  "dutch angle",
  "film grain",
  "film look",
  "film",
  "fisheye lens",
  "focal length",
  "full frame",
  "gopro",
  "high angle",
  "high dynamic range",
  "hasselblad",
  "kodak ektachrome e100",
  "kodak portra 800",
  "macro",
  "medium angle",
  "motion blur",
  "rimlight",
  "shallow depth of field",
  "shallow dof",
  "shallow focus",
  "tiny planet",
  "ultrawide gopro lens",
  "wide angle",
];

const LIGHTING = [
  "cinematic lighting",
  "cool color grading",
  "dramatic lighting",
  "dramatic shadows",
  "florescent lighting",
  "hard lighting",
  "hard shadows",
  "indirect light",
  "indirect lighting",
  "volumetric lighting",
  "warm color grading",
];

const MISC = [
  "4k",
  "8k",
  "epic",
  "eye contact",
  "fine detailing",
  "flat shading",
  "hd",
  "highly detailed",
  "intricate design",
  "intricate detail",
  "movie frame",
  "photorealistic",
  "skin pores",
  "vibrant color",
];

const NEGATIVES = [
  "bad composition",
  "bad lighting",
  "bad quality",
  "bad texture",
  "blurry",
  "cg, painting, drawing, sketch, anime, blender",
  "deformed face",
  "deformed hands",
  "deformed legs",
  "deformed limbs",
  "high contrast",
  "high poly",
  "high quality",
  "long neck",
  "low contrast",
  "low poly",
  "low quality",
  "low resolution",
  "mutated",
  "mutation",
  "sharp",
  "short neck",
  "skin pores",
  "skin texture",
  "text",
  "ugly",
  "watermark",
  "weird",
];

const ACTORS = [
  "Al Pacino",
  "Alan Alda",
  "Alan Arkin",
  "Alan Rickman",
  "Alec Baldwin",
  "Alec Guinness",
  "Alfred Hitchcock",
  "Alfred Molina",
  "Anthony Daniels",
  "Anthony Hopkins",
  "Arnold Schwarzenegger",
  "Arthur Darvill",
  "Ben Affleck",
  "Brad Pitt",
  "Brendan Fraser",
  "Brent Spiner",
  "Bruce Willis",
  "Bryan Cranston",
  "Burt Lancaster",
  "Burt Reynolds",
  "Cary Grant",
  "Charlie Chaplin",
  "Charlie Day",
  "Charlie Sheen",
  "Chris Evans",
  "Chris Hemsworth",
  "Chris Pine",
  "Chris Pratt",
  "Chris Rock",
  "Christian Bale",
  "Clark Gable",
  "Clint Eastwood",
  "Colin Firth",
  "Colm Meaney",
  "Cuba Gooding Jr.",
  "Daniel Craig",
  "Daniel Day-Lewis",
  "Daniel Radcliffe",
  "Danny DeVito",
  "David Mitchell",
  "David Tennant",
  "Deforest Kelley",
  "Denzel Washington",
  "Dustin Hoffman",
  "Dwayne Johnson",
  "Eddie Murphy",
  "Edward Norton",
  "Elijah Wood",
  "Elliot Gould",
  "Ethan Hawke",
  "Ewan McGregor",
  "F. Murray Abraham",
  "Forest Whitaker",
  "Frank Sinatra",
  "Frank Welker",
  "Frank Zappa",
  "Gary Oldman",
  "Gene Hackman",
  "Gene Wilder",
  "George C. Scott",
  "George Carlin",
  "George Clooney",
  "George Lucas",
  "George Takei",
  "Gregory Peck",
  "Harrison Ford",
  "Hugh Jackman",
  "Hugh Laurie",
  "Humphrey Bogart",
  "Ian McKellen",
  "Idris Elba",
  "Jack Black",
  "Jack Nicholson",
  "Jackie Chan",
  "James Cagney",
  "James Dean",
  "James Earl Jones",
  "James Franco",
  "James Gandolfini",
  "Jason Statham",
  "Jeff Bridges",
  "Jeff Daniels",
  "Jeff Goldblum",
  "Jeffrey Wright",
  "Jeremy Irons",
  "Jeremy Renner",
  "Jerry Seinfeld",
  "Jim Belushi",
  "Jim Carrey",
  "Jimmy Carr",
  "Jimmy Stewart",
  "Joe Don Baker",
  "John Travolta",
  "Johnathan Frakes",
  "Johnny Depp",
  "Jon Hamm",
  "Jon Voight",
  "Jonah Hill",
  "Joseph Gordon-Levitt",
  "Keanu Reeves",
  "Kevin Costner",
  "Kevin Smith",
  "Kevin Spacey",
  "Kiefer Sutherland",
  "Kirk Douglas",
  "Kurt Russell",
  "Laurence Fishburne",
  "Laurence Olivier",
  "Leonard Nimoy",
  "Leonardo DiCaprio",
  "LeVar Burton",
  "Liam Neeson",
  "Mark Wahlberg",
  "Marlon Brando",
  "Martin Freeman",
  "Matt Damon",
  "Matt Smith",
  "Matthew McConaughey",
  "Mel Brooks",
  "Mel Gibson",
  "Michael Caine",
  "Michael Cera",
  "Michael Dorn",
  "Michael Douglas",
  "Michael Fassbender",
  "Michael J. Fox",
  "Michael Keaton",
  "Morgan Freeman",
  "Paton Oswalt",
  "Patrick Stewart",
  "Paul Giamatti",
  "Paul Newman",
  "Paul Rudd",
  "Peter Capaldi",
  "Peter Falk",
  "Peter O'Toole",
  "Peter Sellers",
  "Peter Serafinowicz",
  "Philip Seymour Hoffman",
  "Robert De Niro",
  "Robert Downey Jr.",
  "Robert Duvall",
  "Robert Mitchum",
  "Robert Redford",
  "Robert Webb",
  "Robin Williams",
  "Roddy Piper",
  "Rowan Atkinson",
  "Russell Brand",
  "Russell Crowe",
  "Ryan Reynolds",
  "Samuel L. Jackson",
  "Sean Connery",
  "Sean Penn",
  "Seth Rogen",
  "Shia LaBeouf",
  "Sidney Poitier",
  "Spencer Tracy",
  "Stephen Fry",
  "Steve Martin",
  "Steve McQueen",
  "Tom Cruise",
  "Tom Hanks",
  "Tom Hardy",
  "Tommy Lee Jones",
  "Tommy Wiseau",
  "Tony Curtis",
  "Val Kilmer",
  "Viggo Mortensen",
  "Vin Diesel",
  "Vincent D'Onofrio",
  "Wil Wheaton",
  "Will Smith",
  "William Holden",
  "William Shatner",
  "Woody Allen",
  "Woody Harrelson",
  "Yul Brynner",
];

const ACTRESSES = [
  "Amanda Peet",
  "Amanda Plummer",
  "Amanda Seyfried",
  "Amy Adams",
  "Amy Poehler",
  "Angelina Jolie",
  "Anne Hathaway",
  "Audrey Hepburn",
  "Ava Gardner",
  "Barbra Streisand",
  "Bette Davis",
  "Billie Piper",
  "Bjork",
  "Cameron Diaz",
  "Cate Blanchett",
  "Catherine Zeta-Jones",
  "Charlize Theron",
  "Chloe Grace Moretz",
  "Cindy Crawford",
  "Claire Danes",
  "Denise Crosby",
  "Diane Keaton",
  "Diane Lane",
  "Drew Barrymore",
  "Elizabeth Taylor",
  "Emma Stone",
  "Emma Watson",
  "Frances McDormand",
  "Gates McFadden",
  "Gillian Anderson",
  "Ginger Rogers",
  "Glenn Close",
  "Grace Kelly",
  "Greta Garbo",
  "Halle Bailey",
  "Halle Berry",
  "Helen Hunt",
  "Helen Mirren",
  "Hilary Swank",
  "Holly Hunter",
  "Ingrid Bergman",
  "Jane Fonda",
  "Jenna Coleman",
  "Jennifer Aniston",
  "Jennifer Lawrence",
  "Joan Crawford",
  "Jodie Whittaker",
  "Judi Dench",
  "Judy Garland",
  "Julia Roberts",
  "Julianne Moore",
  "Karen Gillan",
  "Kate Winslet",
  "Katherine Hepburn",
  "Keira Knightley",
  "Kirsten Dunst",
  "Kristen Stewart",
  "Kylie Minogue",
  "Lauren Bacall",
  "Lena Headey",
  "Linda Cardellini",
  "Liza Minnelli",
  "Lupita Nyong'o",
  "Madonna",
  "Majel Barrett",
  "Margo Martindale",
  "Margo Robbie",
  "Marilyn Monroe",
  "Marina Sirtis",
  "Marlene Dietrich",
  "Megan Fox",
  "Meryl Streep",
  "Michelle Pfeiffer",
  "Milla Jovovich",
  "Natalie Dormer",
  "Natalie Portman",
  "Nichelle Nichols",
  "Nicole Kidman",
  "Olivia Colman",
  "Olivia Munn",
  "Olivia Wilde",
  "Pearl Mackie",
  "Penelope Cruz",
  "Reese Witherspoon",
  "Renee Zellweger",
  "Rita Hayworth",
  "Sally Field",
  "Salma Hayek",
  "Sandra Bullock",
  "Scarlett Johansson",
  "Sharon Stone",
  "Shirley MacLaine",
  "Sigourney Weaver",
  "Sofia Vergara",
  "Sophia Loren",
  "Susan Sarandon",
  "Tilda Swinton",
  "Uma Thurman",
  "Viola Davis",
  "Vivien Leigh",
  "Zoe Saldana",
];
