const ARTISTS = [
  "al jaffee",
  "ansel adams",
  "drew struzan",
  "greg rutkowski",
  "jack davis",
  "warhol",
];

const ART_STYLES = [
  "3d render",
  "abstract",
  "anime",
  "art deco",
  "art nouveau",
  "caricature",
  "cel shading",
  "dreamworks",
  "dutch renaissance",
  "expressionist",
  "flat shading",
  "forced perspective",
  "futurism",
  "harlem renaissance",
  "hyperrealism",
  "impressionist",
  "metal hurlant",
  "octane render",
  "painting",
  "pixar",
  "pop art",
  "realist",
  "surrealist",
  "unreal engine",
  "vector art",
  "victorian",
  "vintage",
  "watercolor",
  "woodcut",
];

const GALLERIES = ["artstation", "cgsociety"];

const CAMERA_ATTR = [
  "35mm f1.8",
  "analog photo",
  "bird's eye view",
  "close up",
  "distant view",
  "film grain",
  "hasselblad",
  "kodak ektachrome e100",
  "kodak portra 800",
  "macro",
  "medium angle",
  "motion blur",
  "rimlight",
  "shallow depth of field",
  "tiny planet",
  "ultrawide gopro lens",
  "wide angle",
];

const LIGHTING = [
  "cinematic lighting",
  "dramatic lighting",
  "volumetric lighting",
];

const MISC = [
  "4k",
  "8k",
  "epic",
  "eye contact",
  "fine detailing",
  "flat shading",
  "hd",
  "highly detailed",
  "intricate design",
  "intricate detail",
  "movie frame",
  "photorealistic",
  "skin pores",
  "vibrant color",
];

const NEGATIVES = [
  "bad composition",
  "bad lighting",
  "bad quality",
  "blurry",
  "cg, painting, drawing, sketch, anime, blender",
  "deformed face",
  "long neck",
  "low poly",
  "low quality",
  "low resolution",
  "mutated",
  "mutation",
  "text",
  "ugly",
  "watermark",
  "weird",
];

const ACTORS = [
  "Al Pacino",
  "Alan Alda",
  "Alan Arkin",
  "Alan Rickman",
  "Alec Baldwin",
  "Alec Guinness",
  "Alfred Hitchcock",
  "Alfred Molina",
  "Anthony Daniels",
  "Anthony Hopkins",
  "Arnold Schwarzenegger",
  "Ben Affleck",
  "Brad Pitt",
  "Bruce Willis",
  "Bryan Cranston",
  "Burt Lancaster",
  "Burt Reynolds",
  "Cary Grant",
  "Charlie Chaplin",
  "Charlie Day",
  "Charlie Sheen",
  "Chris Evans",
  "Chris Hemsworth",
  "Chris Pine",
  "Chris Pratt",
  "Chris Rock",
  "Christian Bale",
  "Clark Gable",
  "Clint Eastwood",
  "Deforest Kelley",
  "Denzel Washington",
  "Dustin Hoffman",
  "Dwayne Johnson",
  "Eddie Murphy",
  "Edward Norton",
  "Elijah Wood",
  "Elliot Gould",
  "Ethan Hawke",
  "Ewan McGregor",
  "F. Murray Abraham",
  "Forest Whitaker",
  "Frank Sinatra",
  "Gary Oldman",
  "Gene Hackman",
  "Gene Wilder",
  "George C. Scott",
  "George Carlin",
  "George Clooney",
  "George Lucas",
  "George Takei",
  "Gregory Peck",
  "Harrison Ford",
  "Hugh Jackman",
  "Hugh Laurie",
  "Humphrey Bogart",
  "Jack Nicholson",
  "Jackie Chan",
  "James Cagney",
  "James Dean",
  "James Earl Jones",
  "Jim Carrey",
  "Joe Don Baker",
  "John Travolta",
  "Johnny Depp",
  "Keanu Reeves",
  "Kevin Costner",
  "Kevin Smith",
  "Kevin Spacey",
  "Kiefer Sutherland",
  "Kirk Douglas",
  "Kurt Russell",
  "Laurence Fishburne",
  "Laurence Olivier",
  "Leonard Nimoy",
  "Leonardo DiCaprio",
  "Liam Neeson",
  "Mark Wahlberg",
  "Marlon Brando",
  "Matt Damon",
  "Mel Gibson",
  "Michael Douglas",
  "Morgan Freeman",
  "Paton Oswalt",
  "Patrick Stewart",
  "Paul Giamatti",
  "Paul Newman",
  "Paul Rudd",
  "Peter O'Toole",
  "Philip Seymour Hoffman",
  "Robert De Niro",
  "Robert Downey Jr.",
  "Robert Duvall",
  "Robert Mitchum",
  "Robert Redford",
  "Robin Williams",
  "Russell Crowe",
  "Ryan Reynolds",
  "Samuel L. Jackson",
  "Sean Connery",
  "Sidney Poitier",
  "Spencer Tracy",
  "Steve Martin",
  "Steve McQueen",
  "Tom Cruise",
  "Tom Hanks",
  "Tommy Lee Jones",
  "Tommy Wiseau",
  "Viggo Mortensen",
  "Vin Diesel",
  "Vincent D'Onofrio",
  "Will Smith",
  "William Holden",
  "William Shatner",
  "Woody Allen",
  "Woody Harrelson",
  "Yul Brynner",
];

const ACTRESSES = [
  "Amanda Peet",
  "Amanda Plummer",
  "Amanda Seyfried",
  "Amy Adams",
  "Amy Poehler",
  "Angelina Jolie",
  "Anne Hathaway",
  "Audrey Hepburn",
  "Ava Gardner",
  "Barbra Streisand",
  "Bette Davis",
  "Cameron Diaz",
  "Cate Blanchett",
  "Catherine Zeta-Jones",
  "Charlize Theron",
  "Chloe Grace Moretz",
  "Cindy Crawford",
  "Claire Danes",
  "Elizabeth Taylor",
  "Emma Stone",
  "Emma Watson",
  "Frances McDormand",
  "Ginger Rogers",
  "Glenn Close",
  "Grace Kelly",
  "Greta Garbo",
  "Helen Mirren",
  "Ingrid Bergman",
  "Jane Fonda",
  "Jennifer Aniston",
  "Jennifer Lawrence",
  "Joan Crawford",
  "Judi Dench",
  "Judy Garland",
  "Julia Roberts",
  "Julianne Moore",
  "Kate Winslet",
  "Katherine Hepburn",
  "Keira Knightley",
  "Kirsten Dunst",
  "Kristen Stewart",
  "Kylie Minogue",
  "Lauren Bacall",
  "Lena Headey",
  "Linda Cardellini",
  "Liza Minnelli",
  "Lupita Nyong'o",
  "Margo Martindale",
  "Margo Robbie",
  "Marilyn Monroe",
  "Marlene Dietrich",
  "Megan Fox",
  "Meryl Streep",
  "Michelle Pfeiffer",
  "Milla Jovovich",
  "Natalie Dormer",
  "Natalie Portman",
  "Nicole Kidman",
  "Nichelle Nichols",
  "Olivia Colman",
  "Olivia Munn",
  "Olivia Wilde",
  "Penelope Cruz",
  "Reese Witherspoon",
  "Renee Zellweger",
  "Rita Hayworth",
  "Sally Field",
  "Salma Hayek",
  "Sandra Bullock",
  "Scarlett Johansson",
  "Sharon Stone",
  "Shirley MacLaine",
  "Sigourney Weaver",
  "Sofia Vergara",
  "Sophia Loren",
  "Susan Sarandon",
  "Tilda Swinton",
  "Uma Thurman",
  "Viola Davis",
  "Vivien Leigh",
  "Zoe Saldana",
];
